name: Check build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libx11-dev libxinerama-dev libxft-dev libx11-xcb-dev libxcb1-dev libxrandr-dev libpango1.0-dev libgtk-3-dev libev-dev libcairo2-dev libxft-dev libxcb-res0-dev
    - name: clean
      run: make clean
    - name: make
      run: make
    - name: make install
      run: make DESTDIR=$PWD/target install
